language: node_js
node_js: "8"

script:
  - echo "npm test temporarily disabled"
  - npm run test
  - npm run build
  
notifications:
    slack:
    rooms:
    - $SLACK_NOTIFICATION#kaligraphi-notif
    on_success: always
    on_failure: always

before_deploy:
  - cd dist/kalidea/kaligraphi

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
