language: node_js
node_js: "8"

if: tag IS present

script:
  - echo "npm test temporarily disabled"
  - npm run build:lib

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
