language: node_js
node_js: "8"

script:
  - echo "npm test temporarily disabled"
  - npm run build:lib

before_deploy:
  - cd dist/kalidea/kaligraphi

deploy:
  if: tag IS present
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
